### PR TITLE
Documentation On Integrating GitHub Enterprise With Apicurio(Kyecloak)

### PR DESCRIPTION
**Pull request by Surbhi27946**
Hi @EricWittmann 
This PR is for the documentation showing step-by-step process to be followed in order to integrate GitHub Enterprise with the Apicurio KC auth.

Please review it once.

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
This is great!  Thanks so much for the contribution @Surbhi27946

**Comment by Surbhi27946** [comment]
> This is great! Thanks so much for the contribution @Surbhi27946

You'r most welcome :) 
Glad that I could help.

**Comment by Surbhi27946** [comment]
Hi @EricWittmann 
By when this PR will get deployed on the documentation link?

**Comment by EricWittmann** [comment]
It's already there:  https://www.apicur.io/studio/docs/using-github-enterprise

**Pull request merged**
