### PR TITLE
Use new {%- -%} liquid tags to eliminate gratuitous blank spaces in output

### PR DESCRIPTION
**Pull request by msavy**

### CODE REVIEW

**Comment by msavy** [comment]
https://shopify.github.io/liquid/basics/whitespace/

**Comment by msavy** [comment]
This is purely eliminating an annoyance :-).

**Comment by EricWittmann** [comment]
Merged without testing.  Hoo boy!  Let's hope it works. :)

**Comment by msavy** [comment]
Absolute mad lad!

**Pull request merged**
